### ISSUE TITLE
new piwik list

### ISSUE THREAD

**Issue by ncou** [middlewares/referrer-spam#1]
Hi,

Nice plugin, i used your code to do my own plugin, but it think you need to update a part of the code.
1) in composer : change the piwik v1.0 used by the latest version : who is now mamoto v1.1.1
2) the russian domain are now encoded as punycode, so perhaps use the idn_to_ascii function if the intl module is activated, or at least add a dependency for trueV/PunyCode to encode the domain without using the intl module.

Let me know if you want a PR.

**Comment by oscarotero** [comment]
Hi. Thanks for bringing this up. A pull request would be great 👍

**Comment by ncou** [comment]
I will add a dependency to trueV/PunyCode (https://github.com/true/php-punycode) to keep the code more portable. Are you fine with this ?

**Comment by ncou** [comment]
PR is done. I let you close the ticket if all is ok.
Keep up the good work.

**Comment by oscarotero** [comment]
New version v1.1.0 released including this fix.
After some tests I think Phony was no necesary so I've removed.
Thanks for your work!
